---

- name: get current username
  command: id -u -n
  register: user_name

- name: print home directory
  command: echo $HOME
  register: user_home

- name: print username and home dir
  debug:
    msg: "user: {{ user_name.stdout }} --- home: {{ user_home.stdout }}"

- name: test sudo on the pwd command
  become: yes
  command: pwd
  register: sudo_result

- debug:
    var: sudo_result.stdout
