---

- name: set explicit ServerName for default website
  become: yes
  lineinfile:
    dest: /etc/apache2/sites-available/000-default.conf
    regexp: ServerName
    line: ServerName {{ apache_servername }}

- name: get certbot
  command: "{{ item }}"
  with_items:
    - wget https://dl.eff.org/certbot-auto
    - chmod a+x certbot-auto

- name: install certificate
  command: ./certbot-auto --non-interactive {{ cert.additional_flags }} --agree-tos --email {{ cert.email_address }} --apache --domains {{ apache_servername }}

- name: set up cert renewal cron job
  cron:
    name: ssl certificate renewal
    user: "{{ my_remote_user }}"
    job: sleep $(shuf -i 0-59 -n 1)s; ~/certbot-auto renew --no-self-upgrade --dry-run
    disabled: yes

- name: set up cron sleep test job
  cron:
    name: cron sleep test job
    user: "{{ my_remote_user }}"
    job: sleep $(shuf -i 0-59 -n 1)s; date;
