---
- hosts: ansible-pocs-1
  remote_user: "{{ my_remote_user }}"
  become: no
  become_method: sudo
  become_user: root

  tasks:

  # try writing a task with hosts defined at task level?

    - name: sync local folder to remote folder
      synchronize:
        src: /Users/patrick/Documents/syncthis
        dest: /home/admin

    # - name: sync remote folder to remote folder
    #   become: yes
    #   synchronize:
    #     src: /home/admin/syncthis
    #     dest: /home/admin
    #     mode: push 
    #   delegate_to: ansible-pocs-2
