---
- name: rsync with remote machines
  hosts: ansible-pocs-1
  remote_user: admin
  become: no
  become_method: sudo
  become_user: root

  tasks:

    - name: sync local folder to remote folder
      synchronize:
        src: /Users/patrick/Documents/syncthis
        dest: /home/admin

    ## This playbook is run against host ansible-pocs-1, but this task is
    ## delegated to ansible-pocs-2. In practice this means that the task
    ## first logs into ansible-pocs-2 and then runs rsync from there back
    ## to ansible-pocs-1.
    - name: sync remote folder to remote folder
      synchronize:
        src: /home/admin/syncthis
        dest: /home/admin
        # archive: yes ## default is yes
        # recursive: yes ## default is value of 'archive'
        ## hence, it is not necessary to explicitly set recursive: yes
        # mode: push ## default is push
      delegate_to: ansible-pocs-2

    ## This task does the same as the previous task, except we are
    ## supplying the delegate host as a variable - in this case, the
    ## second machine listed in the staging group (index 1).
    - name: sync remote folders using var as delegate
      synchronize:
        src: /home/admin/syncthis
        dest: /home/admin
      delegate_to: "{{ groups['staging'][1] }}"  
